/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminTestimoniRouteImport } from './routes/admin.testimoni'
import { Route as AdminPaketRouteImport } from './routes/admin.paket'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminArmadaRouteImport } from './routes/admin.armada'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimoniRoute = AdminTestimoniRouteImport.update({
  id: '/testimoni',
  path: '/testimoni',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaketRoute = AdminPaketRouteImport.update({
  id: '/paket',
  path: '/paket',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArmadaRoute = AdminArmadaRouteImport.update({
  id: '/armada',
  path: '/armada',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/armada': typeof AdminArmadaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/paket': typeof AdminPaketRoute
  '/admin/testimoni': typeof AdminTestimoniRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/armada': typeof AdminArmadaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/paket': typeof AdminPaketRoute
  '/admin/testimoni': typeof AdminTestimoniRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/armada': typeof AdminArmadaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/paket': typeof AdminPaketRoute
  '/admin/testimoni': typeof AdminTestimoniRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/armada'
    | '/admin/orders'
    | '/admin/paket'
    | '/admin/testimoni'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/armada'
    | '/admin/orders'
    | '/admin/paket'
    | '/admin/testimoni'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/armada'
    | '/admin/orders'
    | '/admin/paket'
    | '/admin/testimoni'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimoni': {
      id: '/admin/testimoni'
      path: '/testimoni'
      fullPath: '/admin/testimoni'
      preLoaderRoute: typeof AdminTestimoniRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paket': {
      id: '/admin/paket'
      path: '/paket'
      fullPath: '/admin/paket'
      preLoaderRoute: typeof AdminPaketRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/armada': {
      id: '/admin/armada'
      path: '/armada'
      fullPath: '/admin/armada'
      preLoaderRoute: typeof AdminArmadaRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminArmadaRoute: typeof AdminArmadaRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaketRoute: typeof AdminPaketRoute
  AdminTestimoniRoute: typeof AdminTestimoniRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArmadaRoute: AdminArmadaRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaketRoute: AdminPaketRoute,
  AdminTestimoniRoute: AdminTestimoniRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
